name: Build LLVM17 Toolchain for Linux

on:
  workflow_dispatch:
  push:
    branches:
      - llvm-17.0.6rel

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-17.0.6rel"
          submodules: "recursive"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt install -y cmake ninja

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=clang -DCLANG_ENABLE_STATIC_ANALYZER=OFF -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_ZSTD=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DCMAKE_INSTALL_PREFIX="./install" ../llvm
          ninja
          ninja install
          tar -czvf Hikari_LLVM17.0.6.linux.tar.gz ./install
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Hikari_LLVM17.0.6.linux.tar.gz
          path: build/Hikari_LLVM17.0.6.linux.tar.gz
